services:
  app:
    image: WagnerZaneboneCapelini/Curso_FastAPI_Template_Backend-app:dev
    build:
      context: .
      target: app
    environment:
      - ENVIRONMENT=dev
    env_file:
      - dev.env
    volumes:
      - .:/workspaces/Curso_FastAPI_Template_Backend
    # command: uvicorn Curso_FastAPI_Template_Backend.api:app --host 0.0.0.0 --port 8000 --reload
    command: ["api", "--dev"]

  dozzle:
      image: amir20/dozzle:latest
      restart: always
      environment:
        DOZZLE_LEVEL: debug
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 8088:8080
      profiles:
        - app
        - dev


  db:
    image: postgres:16.3
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
  pgadmin:
    image: dpage/pgadmin4:9.1
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - pgadmin_data:/home/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
